export const catalogs = [
  {
    name: "Electronics",
    id: "electronics",
    image: "/images/electronics_catalog.jpg",
    link: "/category/electronics",
    subcategory: ["Phones", "Computer", "Headphones", "TV"],
  },
  {
    name: "Videogame & Console",
    id: "videogame&console",
    image: "/images/console_videogame_catalog.jpg",
    link: "/category/videogame&console",
    subcategory: ["Console", "Videogame"],
  },
  {
    name: "Clothes",
    id: "clothes",
    image: "/images/clothes_catalog.jpg",
    link: "/category/clothes",
    subcategory: ["Jeans", "Shoes", "Shirt", "Jacket"],
  },
  {
    name: "Pets supplies",
    id: "petsSupplies",
    image: "/images/pets_catalog.jpg",
    link: "/category/petsSupplies",
    subcategory: ["Food", "Toy"],
  },
  {
    name: "Books",
    id: "books",
    image: "/images/books_catalog.jpg",
    link: "/category/books",
    subcategory: ["Romantic", "Fantasy", "Horror"],
  },
  {
    name: "Personal care",
    id: "personalCare",
    image: "/images/personal_care_catalog.jpg",
    link: "/category/personalCare",
    subcategory: ["Shampoo", "Cream", "Soap"],
  },
  {
    name: "Kitchen product",
    id: "kitchenProduct",
    image: "/images/kitchen_catalog.jpg",
    link: "/category/kitchenProduct",
    subcategory: ["Electronics", "Cleaning"],
  },
]; 
