export const catalogs = [
  {
    name: "Electronics",
    id: "electronics",
    image: "/images/electronic_devices_catalog.jpeg",
    link: "/category/electronics",
    subcategory: ["Phones", "Computer", "Headphones", "TV"],
  },
  {
    name: "Videogame & Console",
    id: "videogame&console",
    image: "/images/console_videogame_catalog.jpeg",
    link: "/category/videogame&console",
    subcategory: ["console", "videogame"],
  },
  {
    name: "Clothes",
    id: "clothes",
    image: "/images/clothes_catalog.jpeg",
    link: "/category/clothes",
    subcategory: ["jeans", "shoes", "shirt", "jacket"],
  },
  {
    name: "Pets supplies",
    id: "petsSupplies",
    image: "/images/pets_catalog.jpeg",
    link: "/category/petsSupplies",
    subcategory: ["food", "toy"],
  },
  {
    name: "Books",
    id: "books",
    image: "/images/books_catalog.jpeg",
    link: "/category/Books",
    subcategory: ["romantic", "fantasy", "horror"],
  },
  {
    name: "Personal care",
    id: "personalCare",
    image: "/images/personal_care_catalog.jpeg",
    link: "/category/personalCare",
    subcategory: ["shampoo", "cream", "soap"],
  },
  {
    name: "Kitchen product",
    id: "kitchenProduct",
    image: "/images/kitchen_catalog.jpeg",
    link: "/category/kitchenProduct",
    subcategory: ["electronics", "cleaning"],
  },
];
